//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honeycomb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrawlerConnection
    {
        public CrawlerConnection()
        {
            this.Batches = new HashSet<Batch>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime ConnectionTime { get; set; }
        public string CrawlerName { get; set; }
        public string CrawlerIP { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
    }
}
