//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honeycomb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crawler_Setting
    {
        public int PageId { get; set; }
        public int MaxLevel { get; set; }
    }
}
