//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honeycomb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Crawler_DBEntities : DbContext
    {
        public Crawler_DBEntities()
            : base("name=Crawler_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BadLink> BadLinks { get; set; }
        public virtual DbSet<Crawler_Setting> Crawler_Settings { get; set; }
        public virtual DbSet<ExternalLink> ExternalLinks { get; set; }
        public virtual DbSet<InternalLink> InternalLinks { get; set; }
        public virtual DbSet<Seed> Seeds { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<CrawlerConnection> CrawlerConnections { get; set; }
        public virtual DbSet<PredefinedJob> PredefinedJobs { get; set; }
    
        public virtual int CleanContent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CleanContent");
        }
    }
}
