//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honeycomb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalLink
    {
        public int LinkId { get; set; }
        public string LinkPath { get; set; }
        public string LinkAnchor { get; set; }
        public string PageSeedLink { get; set; }
        public string OriginalPageLink { get; set; }
        public Nullable<double> LinkWeight { get; set; }
        public int OriginalPageLevel { get; set; }
        public Nullable<int> LinkCount { get; set; }
    }
}
