//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honeycomb
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalLink
    {
        public int PageId { get; set; }
        public int PageIdSeedSpecific { get; set; }
        public string PageLink { get; set; }
        public string PageSeedLink { get; set; }
        public string OriginalPageLink { get; set; }
        public int PageLevel { get; set; }
        public bool IsProcessed { get; set; }
        public bool IsAvailable { get; set; }
        public bool IsHtml { get; set; }
        public int LinkCount { get; set; }
    }
}
